variable "FCRname" {}
variable "FCRlocation" {}
variable "FCRtype" {}
variable "emails" {}
variable "Equinixpurchaseorder" {}
variable "FCRmetrocode" {}
variable "FCRpackage" {}
variable "Equinixprojectid" {}
variable "account_number" {}
